{
 "title": "SuperSale API - Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP p95 latency (s) by URI",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "RPS by URI",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx error rate %",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "error%"
    }
   ]
  },
  {
   "title": "JVM Heap Used (bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "heap used"
    }
   ]
  }
 ]
}