CREATE TABLE IF NOT EXISTS RESERVATIONS (
  ID VARCHAR2(36) PRIMARY KEY,
  USER_ID VARCHAR2(36) NOT NULL,
  HOTEL_ID VARCHAR2(36) NOT NULL,
  CHECK_IN DATE NOT NULL,
  CHECK_OUT DATE NOT NULL,
  TOTAL_PRICE NUMBER(12,2) NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'CREATED' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_RES_HOTEL ON RESERVATIONS(HOTEL_ID, CHECK_IN, CHECK_OUT);
